# Generated by Django 4.2.9 on 2024-01-05 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tracking_number", models.CharField(max_length=100)),
                ("carrier", models.CharField(max_length=100)),
                ("sender_address", models.TextField()),
                ("receiver_address", models.TextField()),
                ("status", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article_name", models.CharField(max_length=100)),
                ("article_quantity", models.IntegerField()),
                ("article_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("SKU", models.CharField(max_length=50)),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ShipTrackWeather.shipment",
                    ),
                ),
            ],
        ),
    ]
